## Author: Matt Ryan
## Date: 21/11/2020

## This script assumes you have pacman and gapminder installed
## This script assumes you have folders raw_data and data
## This will clean the data downloaded by 01_download_data

## Packages
pacman::p_load(tidyverse, easyPubMed, gender, predictrace, glue)

## Read in and ready data
pubmed_df <- read_csv("raw_data/raw_pubmed.csv") # This is the data generated by "01_download_data"

# Load in a list of 142 countries from the gapminder package
countries <- unique(gapminder::gapminder$country) %>% 
  as.character()
# Convert to a logical string statement
countries <- str_to_lower(str_c(countries, collapse = "|") )

# Read in a list educational institutes in Australia courtesy of
# https://data.gov.au/data/dataset/tqnr/resource/07370e3f-780b-4a70-8c87-b6796d5ab237
institute_names <- read_csv("raw_data/providers_19112020a.csv") %>% 
  select(ProviderName, Category)

institute_names_list <- institute_names %>% 
  filter(Category == "Australian University") %>% # Filter to get universtities only
  mutate(ProviderName = str_remove(ProviderName, "Pty"),
         ProviderName = str_remove(ProviderName, "Ltd"), # Remove some annoying characters
         ProviderName = str_remove(ProviderName, "The "),
         ProviderName = str_extract(ProviderName, "[^(]+"),
         ProviderName = str_remove(ProviderName, "Limited"),
         ProviderName = str_remove(ProviderName, "[.]")) %>% 
  pull(ProviderName) 
# Convert to a logical string statement
institute_names_list <- str_c(str_to_lower(institute_names_list), collapse = "|")

## Perform the first step of cleaning
# Drop the email field
# Add the order of authors and the total number of authors on a paper
# Select only first and last authors
# Convert numeric ordering to First author, Last author, or Single author
# Remove any initials from the first name for gender matching
# Extract country from address, THIS IS NOT PERFECT
# Extract institute from address, THIS IS NOT PERFECT
pubmed_df_cleaning <- pubmed_df %>% 
  select(-email) %>% 
  group_by(pmid) %>% 
  mutate(num_authors = length(title), order = row_number()) %>% 
  filter(order == max(order) | order == min(order)) %>% 
  mutate(order = ifelse(order == 1, "First", "Last"),
         order = ifelse(num_authors == 1, "Single", order)) %>% 
  ungroup() %>% 
  mutate(firstname = str_extract(firstname, "[^ ]+"),
         country = str_extract(str_to_lower(address), 
                               countries),
         institute = str_extract(str_to_lower(address), institute_names_list)) 

# Use the gender package to gender match based on first name, remove any repeats
gender_test <- gender(pubmed_df_cleaning$firstname) %>% 
  select(firstname = name, gender) %>% 
  distinct(firstname, .keep_all = TRUE)

# Join the gender matched names to the cleaned data
pubmed_gender_matched <- left_join(pubmed_df_cleaning, gender_test, by = "firstname")

# Use the predictrace package to predict race based on last name
race_test <- predict_race(pubmed_gender_matched$lastname, probability = FALSE) %>% 
  select(lastname = name, race = likely_race) %>% 
  distinct(lastname, .keep_all = TRUE)

# Join the race matched data to the gender matched data
pubmed_race_matched <- left_join(pubmed_gender_matched, race_test, by = "lastname")

# Filter to publications by authors in Australia, include NA as we are not sure where they are from.
pubmed_final <- pubmed_race_matched %>% 
  filter(country == "australia" | is.na(country))

# Save the output as a csv
write_csv(pubmed_final, "data/pubmed_cleaned.csv")








